# Generated by Django 4.0.6 on 2025-04-24 11:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0016_alter_invoicecreatemodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemaingInventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color_remaing_keles', to='index.colormodel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_remaing_keles', to='index.categorymodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='size_remaing_keles', to='index.sizemodel')),
            ],
            options={
                'verbose_name': 'RemaingModel',
                'verbose_name_plural': 'RemaingModel',
            },
        ),
        migrations.CreateModel(
            name='ProductEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color_from_keles', to='index.colormodel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_from_keles', to='index.categorymodel')),
                ('product_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_from_keles', to='index.transferfrominventory')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='size_from_keles', to='index.sizemodel')),
            ],
            options={
                'verbose_name': 'ProductEntry',
                'verbose_name_plural': 'ProductEntry',
            },
        ),
        migrations.CreateModel(
            name='InvoiceCreateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='color_invoice_keles', to='index.colormodel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_keles', to='index.categorymodel')),
                ('product_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_to_keles', to='index.transfertoinventory')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='size_invoice_keles', to='index.sizemodel')),
            ],
            options={
                'verbose_name': 'InvoiceModel',
                'verbose_name_plural': 'InvoiceModels',
                'ordering': ['name'],
            },
        ),
    ]
