# Generated by Django 4.0.6 on 2025-05-15 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        ('keles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceKeles',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.transfertoinventory')),
            ],
        ),
    ]
