# Generated by Django 4.0.6 on 2025-04-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_alter_invoicecreatemodel_options_and_more'),
        ('keles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceCreateModel',
            new_name='InvoiceCreateKeles',
        ),
        migrations.RenameModel(
            old_name='ProductEntry',
            new_name='ProductEntryKeles',
        ),
        migrations.RenameModel(
            old_name='RemaingInventoryModel',
            new_name='RemaingInventoryKeles',
        ),
    ]
