# Generated by Django 4.0.6 on 2025-05-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keles', '0002_invoicekeles'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecreatekeles',
            name='invoice',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='keles.invoicekeles'),
            preserve_default=False,
        ),
    ]
