# Generated by Django 4.0.6 on 2025-04-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='title')),
                ('title_en', models.CharField(max_length=10, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=10, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=10, null=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=100, null=True, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='TransferToInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=100, null=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'TransferToInventory',
                'verbose_name_plural': 'TransferToInventory',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='index.categorymodel')),
                ('product_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.transfertoinventory')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.sizemodel')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product Models',
                'ordering': ['name'],
            },
        ),
    ]
