# Generated by Django 4.0.2 on 2022-02-24 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(max_length=4)),
                ('inventar_number', models.IntegerField(max_length=16, unique=True)),
                ('processor', models.CharField(max_length=70)),
                ('memory', models.CharField(max_length=70)),
                ('keyword_mouse', models.CharField(max_length=6)),
                ('mac_address', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('qr_code', models.ImageField(blank=True, upload_to='images/code')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.category')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.model')),
                ('responsible_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.responsible')),
            ],
        ),
    ]
