# Generated by Django 4.0.6 on 2025-05-15 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'CategoryModel',
                'verbose_name_plural': 'CategoryModel',
            },
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'ColorModel',
                'verbose_name_plural': 'ColorsModel',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransferFromInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TransferFromInventory',
                'verbose_name_plural': 'TransferFromInventory',
            },
        ),
        migrations.CreateModel(
            name='TransferToInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TransferToInventory',
                'verbose_name_plural': 'TransferToInventory',
            },
        ),
        migrations.CreateModel(
            name='RemaingInventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color_remaing', to='index.colormodel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_remaing', to='index.categorymodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='size_remaing', to='index.sizemodel')),
            ],
            options={
                'verbose_name': 'RemaingModel',
                'verbose_name_plural': 'RemaingModel',
            },
        ),
        migrations.CreateModel(
            name='ProductPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='index.colormodel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.categorymodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.sizemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color_from', to='index.colormodel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_from', to='index.categorymodel')),
                ('product_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_from', to='index.transferfrominventory')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='size_from', to='index.sizemodel')),
            ],
            options={
                'verbose_name': 'ProductEntry',
                'verbose_name_plural': 'ProductEntry',
            },
        ),
        migrations.CreateModel(
            name='InvoiceCreateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='color_invoice', to='index.colormodel')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='index.invoice')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='index.categorymodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.sizemodel')),
            ],
            options={
                'verbose_name': 'InvoiceModel',
                'verbose_name_plural': 'InvoiceModels',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='product_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.transfertoinventory'),
        ),
    ]
