# Generated by Django 4.0.2 on 2022-02-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventar_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
