# Generated by Django 4.0.2 on 2022-03-01 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_product_inventar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='index.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventar_number',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='keyword_mouse',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
