# Generated by Django 4.0.2 on 2022-03-02 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_product_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='index.category'),
        ),
    ]
