# Generated by Django 4.0.6 on 2025-04-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_productmodel_code_alter_productmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ColorModel',
                'verbose_name_plural': 'ColorsModel',
            },
        ),
        migrations.CreateModel(
            name='TransferFromInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TransferFromInventory',
                'verbose_name_plural': 'TransferFromInventory',
            },
        ),
    ]
