# Generated by Django 4.0.2 on 2022-03-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_product_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='room_number',
            field=models.CharField(max_length=4),
        ),
    ]
