# Generated by Django 4.0.6 on 2025-04-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_colormodel_transferfrominventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='sizemodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='sizemodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='sizemodel',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='transfertoinventory',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='transfertoinventory',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='transfertoinventory',
            name='title_uz',
        ),
    ]
