# Generated by Django 4.0.2 on 2022-03-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_product_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
