# Generated by Django 4.0.6 on 2025-04-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_categorymodel_title_en_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='InvoiceCreateModel',
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='title',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transfertoinventory',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
