# Generated by Django 4.0.2 on 2022-03-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_product_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='room_number',
            field=models.CharField(max_length=4),
        ),
    ]
