# Generated by Django 4.0.6 on 2025-04-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_rename_productmodel_invoicecreatemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicecreatemodel',
            name='code',
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
