# Generated by Django 4.0.6 on 2025-04-08 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_invoicecreatemodel_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'CategoryModel', 'verbose_name_plural': 'CategoryModel'},
        ),
        migrations.CreateModel(
            name='ProductFromInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_from', to='index.categorymodel')),
                ('product_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_from', to='index.transferfrominventory')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='size_from', to='index.sizemodel')),
            ],
            options={
                'verbose_name': 'ProductFromInventory',
                'verbose_name_plural': 'ProductFromInventory',
            },
        ),
    ]
