# Generated by Django 4.0.2 on 2022-03-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_product_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
