# Generated by Django 4.0.2 on 2022-03-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='Ishlatilmoqda', max_length=40, null=True),
        ),
    ]
