# Generated by Django 4.0.6 on 2025-04-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_categorymodel_options_productfrominventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecreatemodel',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='color_invoice', to='index.colormodel'),
        ),
        migrations.AddField(
            model_name='productfrominventory',
            name='color',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='color_from', to='index.colormodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RemaingInventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color_remaing', to='index.colormodel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_remaing', to='index.categorymodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='size_remaing', to='index.sizemodel')),
            ],
            options={
                'verbose_name': 'RemaingModel',
                'verbose_name_plural': 'RemaingModel',
            },
        ),
    ]
