# Generated by Django 4.0.2 on 2022-03-09 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='index.model'),
        ),
    ]
