# Generated by Django 4.0.6 on 2025-04-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_invoicecreatemodel_color_productfrominventory_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
