# Generated by Django 4.0.2 on 2022-03-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_product_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='index.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='index.model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='responsible_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.responsible'),
        ),
    ]
