# Generated by Django 4.0.6 on 2025-04-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_categorymodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicecreatemodel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='color_invoice', to='index.colormodel'),
        ),
    ]
