# Generated by Django 4.0.6 on 2025-04-09 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_invoicecreatemodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicecreatemodel',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
