# Generated by Django 4.0.1 on 2022-06-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_product_category_id_alter_product_model_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seria_raqami',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
