# Generated by Django 4.0.6 on 2025-04-09 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_invoicecreatemodel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color_from', to='index.colormodel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_from', to='index.categorymodel')),
                ('product_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_from', to='index.transferfrominventory')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='size_from', to='index.sizemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductFromInventory',
        ),
    ]
