# Generated by Django 4.0.1 on 2022-06-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_product_seria_raqami'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seria_raqami',
            new_name='seria_number',
        ),
    ]
