# Generated by Django 4.0.6 on 2025-04-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_productentry_delete_productfrominventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productentry',
            options={'verbose_name': 'ProductFromInventory', 'verbose_name_plural': 'ProductFromInventory'},
        ),
    ]
