# Generated by Django 4.0.1 on 2022-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_rename_seria_raqami_product_seria_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seria_number',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
