# Generated by Django 4.0.6 on 2025-04-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_alter_productentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicecreatemodel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_invoice', to='index.colormodel'),
        ),
        migrations.AlterField(
            model_name='invoicecreatemodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='index.categorymodel'),
        ),
        migrations.AlterField(
            model_name='invoicecreatemodel',
            name='product_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.transfertoinventory'),
        ),
        migrations.AlterField(
            model_name='invoicecreatemodel',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.sizemodel'),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_from', to='index.colormodel'),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_from', to='index.categorymodel'),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='product_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='index.transferfrominventory'),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_from', to='index.sizemodel'),
        ),
        migrations.AlterField(
            model_name='remainginventorymodel',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_remaing', to='index.colormodel'),
        ),
        migrations.AlterField(
            model_name='remainginventorymodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_remaing', to='index.categorymodel'),
        ),
        migrations.AlterField(
            model_name='remainginventorymodel',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_remaing', to='index.sizemodel'),
        ),
    ]
