# Generated by Django 4.0.2 on 2022-06-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
