# Generated by Django 4.0.6 on 2025-05-10 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_alter_invoicecreatemodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.colormodel')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.categorymodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.sizemodel')),
            ],
        ),
    ]
