# Generated by Django 4.0.6 on 2022-08-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_product_responsible_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default=5, upload_to='person'),
            preserve_default=False,
        ),
    ]
