# Generated by Django 4.0.6 on 2022-08-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_roomsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsmodel',
            name='created_at',
        ),
    ]
