# Generated by Django 4.0.6 on 2022-08-18 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_remove_roomsmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='model',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='model',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='model',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='fullname_en',
            field=models.CharField(max_length=100, null=True, verbose_name='fullname'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='fullname_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='fullname'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='fullname_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='fullname'),
        ),
        migrations.AddField(
            model_name='roomsmodel',
            name='floor_en',
            field=models.CharField(max_length=10, null=True, verbose_name='floor'),
        ),
        migrations.AddField(
            model_name='roomsmodel',
            name='floor_ru',
            field=models.CharField(max_length=10, null=True, verbose_name='floor'),
        ),
        migrations.AddField(
            model_name='roomsmodel',
            name='floor_uz',
            field=models.CharField(max_length=10, null=True, verbose_name='floor'),
        ),
        migrations.AddField(
            model_name='roomsmodel',
            name='rooms_en',
            field=models.CharField(max_length=10, null=True, verbose_name='rooms'),
        ),
        migrations.AddField(
            model_name='roomsmodel',
            name='rooms_ru',
            field=models.CharField(max_length=10, null=True, verbose_name='rooms'),
        ),
        migrations.AddField(
            model_name='roomsmodel',
            name='rooms_uz',
            field=models.CharField(max_length=10, null=True, verbose_name='rooms'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='static/images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='model',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='model',
            name='image',
            field=models.ImageField(upload_to='static/images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='index.category', verbose_name='category_id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='person', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventar_number',
            field=models.IntegerField(blank=True, unique=True, verbose_name='inventar_number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='ip_address'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keyword_mouse',
            field=models.CharField(blank=True, max_length=6, verbose_name='keyword_mouse'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='mac_address'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.CharField(blank=True, max_length=70, verbose_name='memory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='index.model', verbose_name='model_id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, max_length=70, verbose_name='processor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='images/code', verbose_name='qr_code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='responsible_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.responsible', verbose_name='responsible_id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='responsible_person'),
        ),
        migrations.AlterField(
            model_name='product',
            name='room_number',
            field=models.CharField(max_length=4, verbose_name='room_number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seria_number',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='seria_number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='Ishlatilmoqda', max_length=40, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='floor',
            field=models.CharField(max_length=10, verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='roomsmodel',
            name='rooms',
            field=models.CharField(max_length=10, verbose_name='rooms'),
        ),
    ]
