# Generated by Django 4.0.6 on 2022-08-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='responsible_person_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='responsible_person'),
        ),
        migrations.AddField(
            model_name='product',
            name='responsible_person_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='responsible_person'),
        ),
        migrations.AddField(
            model_name='product',
            name='responsible_person_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='responsible_person'),
        ),
        migrations.AddField(
            model_name='product',
            name='status_en',
            field=models.CharField(default='Ishlatilmoqda', max_length=40, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='product',
            name='status_ru',
            field=models.CharField(default='Ishlatilmoqda', max_length=40, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='product',
            name='status_uz',
            field=models.CharField(default='Ishlatilmoqda', max_length=40, null=True, verbose_name='status'),
        ),
    ]
