# Generated by Django 4.0.6 on 2022-08-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_product_description_en_product_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsmodel',
            name='floor_en',
        ),
        migrations.RemoveField(
            model_name='roomsmodel',
            name='floor_ru',
        ),
        migrations.RemoveField(
            model_name='roomsmodel',
            name='floor_uz',
        ),
        migrations.RemoveField(
            model_name='roomsmodel',
            name='rooms_en',
        ),
        migrations.RemoveField(
            model_name='roomsmodel',
            name='rooms_ru',
        ),
        migrations.RemoveField(
            model_name='roomsmodel',
            name='rooms_uz',
        ),
    ]
