# Generated by Django 4.0.6 on 2022-08-19 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_remove_roomsmodel_floor_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='model',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='model',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='model',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='model',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='model',
            name='name_uz',
        ),
    ]
